; Zero Page custom variables

ZP_PTR              = $30    ; temporary pointer #1
ZP_PTR_LO           = $30
ZP_PTR_HI           = $31

ZP_TILE_INDEX       = $35    ; counts tiles in tile bitmap data or on screen
ZP_TILE_ROW         = $36    ; screen tile row
ZP_TILE_COL         = $37    ; screen tile column
ZP_CHAR_CNT         = $38    ; number of characters to show

ZP_PTR2             = $3A    ; temporary pointer #2
ZP_PTR2_LO          = $3A
ZP_PTR2_HI          = $3B
